services:

  server:
    image: blogapp-back-prod
    build:
      context: ./backend/
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=5000
      - NODE-ENV=production
    container_name: blogapp-back-prod
  
  app:
    image: blogapp-front-prod
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
      - /usr/src/app/node_modules
    container_name: blogapp-front-prod
  
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-blogapp-prod
    depends_on:
      - app
      - server